# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import pandas as pd

st.title("analizador de datos ")
st.title("sube un archivo para visualizar los datos en la grafica automatica")

#componente para subir el archivo desde la web
archivo_subido=st.file_uploader("Elige un archivo Csv", type=["csv"])

if archivo_subido is not None :
  #2. Leer el archivo CSV usando pandas
  df= pd.read_csv(archivo_subido)

  # 3 mostrar una vista previa de la tabla en la pagina
  st.subheader("Vista previa de la tabla")
  st.write(df.head())

  # 4.intentar graficar las columnas numericas de forma automatica
  st.subheader("grafica de lineas ")
  columnas_numericas=df.select_dtypes(include=["number"]).columns

  if len(columnas_numericas)>0:
    columna_elegida= st.selectbox("selecciona la columna que quiere graficar:",columnas_numericas)
    st.line_chart(df[columnas_elegidas])
  else:
    st.warning("El archivo CSV no contiene columnas con datos numericos para graficar")

